### ISSUE TITLE
onSaveEvent is called n+1 times per use

### ISSUE THREAD

**Issue by JedWatson** [RepairShopr/react-native-signature-capture#1]
I've implemented `react-native-signature-panel` in an app that uses the `Navigator` component to display it as required, and found that the `onSaveEvent` callback is called +1 times for each time I mount the scene.

Example code:

```
const React = require('react-native');
const SignatureCapture = require('react-native-signature-capture');

const {
	StyleSheet,
	View,
} = React;

var SignatureInput = React.createClass({
	componentWillUnmount () {
		console.log('UNMOUNTING');
	},
	onSave (result) {
		console.log('ONSAVE');
		this.props.onSave(result);
		this.props.navigator.pop();
	},
	render() {
		return (
			<View style={styles.view}>
				<SignatureCapture onSaveEvent={this.onSave}/>
			</View>
		);
	}
});

var styles = StyleSheet.create({
	view: {
		flex: 1
	},
});

module.exports = SignatureInput;
```

In the console, the first time the scene is mounted and the `onSaveEvent` callback fires, everything happens as expected.

The second time, however, `ONSAVE` is logged twice. Third time, it's logged three times. And so on.

**Comment by jedt** [comment]
Hey Jed, 

I was able to replicate and it is now fixed. Kindly test on your end.

commit:
https://github.com/RepairShopr/react-native-signature-capture/commit/4f13e247f98bf810067f0d9a4186f7455c28b908

**Comment by MrHubble** [comment]
I believe I am also experiencing this with `react-navigation` with [nested navigators](https://reactnavigation.org/docs/intro/nesting)
