### ISSUE TITLE
SDK Build Tools revision (23.0.1) is too low build error for Android

### ISSUE THREAD

**Issue by iainheng** [RepairShopr/react-native-signature-capture#134]
I am getting error when trying to build for Android with React Native 0.55.4.

```
The SDK Build Tools revision (23.0.1) is too low for project ':react-native-signature-capture'. Minimum required is 25.0.0
```

Any help of workaround is very much appreciated.

**Comment by SanchitB23** [comment]
> Go to _node_modules/react-native-signature-capture/android/build.gradle_


and Change to this -
`    buildToolsVersion "25.0.0"
`

When you run `react-native run-android`, it'll download whatever and make it work

**Comment by iainheng** [comment]
Thanks for the tip. 👍 I did the same earlier and it works but modify the source files inside `node_modules` isn't ideal as changes will be replaced by future update to the package. Isn't it?

**Comment by lucasriondel** [comment]
@iainheng found a solution. 
Add this to your android/build.gradle : 

`
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27
                buildToolsVersion "27.0.2"
            }
        }
    }
}
`

**Comment by iainheng** [comment]
@lucasriondel Thanks for your solution. It works beautifully. 👍

**Comment by vinicfrancisco** [comment]
@iainheng i've tried your solution using sdk version 28 : 

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion "28.0.3"
            }
        }
    }
}

But I still have the same error: 
compile version (23.0.1)  runtime(28.0.0)

**Comment by vinicfrancisco** [comment]
@iainheng I've tried your solution with sdk 28 but still have the same error

`subprojects {
    afterEvaluate {project ->
           if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion "28.0.3"
            }
        }
    }
}`


compile version(23.0.1) runtime (28.0.0)
