### ISSUE TITLE
with RN > 0.24.0 UIManager is not recognized anymore

### ISSUE THREAD

**Issue by rpopovici** [RepairShopr/react-native-signature-capture#15]
Trying to include UIManager from React package works, but onSaveEvent is not firing anymore on iOS
 
var {
    PropTypes,
    requireNativeComponent,
    UIManager,
    View,
} = React;

**Comment by rpopovici** [comment]
it looks like the problem was introduced with the latest commits

**Comment by jedt** [comment]
ping @john1jan

**Comment by john1jan** [comment]
looking into it

**Comment by john1jan** [comment]
@rpopovici I have no idea about IOS. But in Android i have upgraded my RN version to "^0.24.0" and tested. It works fine. I am getting the onSaveEvent as well.

**Comment by john1jan** [comment]
check this links https://github.com/facebook/react-native/issues/2260
And i can UIManager used in the ios docs aswell
https://facebook.github.io/react-native/docs/native-components-ios.html#styles

**Comment by rpopovici** [comment]
This is the error I get. I tried everything I could think of, but no luck

![simulator screen shot 19 apr 2016 17 55 14](https://cloud.githubusercontent.com/assets/2832454/14644131/a05a9ea6-0659-11e6-9b9a-a7c590e17063.png)

**Comment by john1jan** [comment]
did you try this https://github.com/facebook/react-native/issues/4968

**Comment by rpopovici** [comment]
Yes, I tried that too. No luck. I will try to recreate the project from scratch. Maybe that helps

**Comment by adba** [comment]
This should be fixed with the latest merge on master #17

**Comment by john1jan** [comment]
@rpopovici can you close this issue
