### ISSUE TITLE
How can I change the thickness of a line?

### ISSUE THREAD

**Issue by csjiabin** [RepairShopr/react-native-signature-capture#160]
How can I change the thickness of a line?

**Comment by danielsouzapinna** [comment]
Can you figure it out? I'm trying to uncover ...

**Comment by freightlive** [comment]
https://github.com/RepairShopr/react-native-signature-capture/blob/master/android/src/main/java/com/rssignaturecapture/RSSignatureCaptureViewManager.java

Hidden features :)

                                minStrokeWidth={4}
                                maxStrokeWidth={4}

**Comment by erickhabil** [comment]
> https://github.com/RepairShopr/react-native-signature-capture/blob/master/android/src/main/java/com/rssignaturecapture/RSSignatureCaptureViewManager.java
> 
> Hidden features :)
> 
> ```
>                             minStrokeWidth={4}
>                             maxStrokeWidth={4}
> ```

Thanks a lot! This worked for me :D

**Comment by SyedShahbazHussain** [comment]
>  minStrokeWidth={4}
>                             maxStrokeWidth={4}

Thanks

**Comment by bernarddoci** [comment]
> https://github.com/RepairShopr/react-native-signature-capture/blob/master/android/src/main/java/com/rssignaturecapture/RSSignatureCaptureViewManager.java
> 
> Hidden features :)
> 
> ```
>                             minStrokeWidth={4}
>                             maxStrokeWidth={4}
> ```How to use this with TypeScript

**Comment by bernarddoci** [comment]
How to use this with TypeScript
