### ISSUE TITLE
the method `saveImage` cannot get `encoded` and `path` parameters

### ISSUE THREAD

**Issue by chj-damon** [RepairShopr/react-native-signature-capture#165]
If I write like this, I can get encoded and path:
```
<SignatureCapture
  style={[{ flex: 1 }, styles.signature]}
  showNativeButtons={false}
  viewMode="landscape"
  onSaveEvent={this.handleSave}
/>

handleSave = ({encoded, path}) => {
 // I can get encoded and path
}
```

But if I use `refs`, I cannot get them:
```
<SignatureCapture
  ref={this.signRef}
  style={[{ flex: 1 }, styles.signature]}
  showNativeButtons={false}
  viewMode="landscape"
/>
<Button style={styles.btn} onPress={this.saveSignature}>
  <Text>保存</Text>
</Button>

saveSignature = () => {
  this.signRef.current.saveImage(({encoded, path}) => {
    // I cannot get encoded and path here.
  });
}
```

Can anyone tell me where I did wrong?

**Comment by layounisl** [comment]
I believe the saveImage() is not a promise so it doesnt have a callback, it will dispatch the action to save the signature, but u will get the encoded and path on the "onSaveEvent" props.
you can use the ref to call the saveImage() method like `this.signRef.saveImage()` , but simply wait the result on the onSaveEvent. 
hope this helped.

**Comment by chj-damon** [comment]
@layounisl thanks for your help. It works if I also listen to the `onSaveEvent`, as you explained, `saveImage` will trigger `onSaveEvent`.
