### ISSUE TITLE
How to store all png image in device

### ISSUE THREAD

**Issue by RavindraMaddukuri** [RepairShopr/react-native-signature-capture#175]
In my project, the png image is replacing by the new image in the storage folder.  but I need all the png image.
and my code is given below.
`import React,{Component} from 'react'
import { StyleSheet, Text, View } from 'react-native'
import DesignSignatureUI from "./DesignSignatureUI"
import SignatureCapture from 'react-native-signature-capture';

export default class RNSignatureExample extends Component {
    constructor(){
        super()
        this.state={
            dragged:false
        }
        this.saveSign = this.saveSign.bind(this)
        this._onDragEvent =  this._onDragEvent.bind(this)
    }
    render() {
        return (
            <View style={{ flex: 1, flexDirection: "column",}}>
                <Text style={{alignItems:"center",justifyContent:"center"}}>{this.props.titleText}</Text>
                <View style={{flex:0.7}}>
                <SignatureCapture
                    style={[{flex:1},styles.signature]}
                    ref={sign => this.signComponent = sign}
                    onSaveEvent={this._onSaveEvent}
                    onDragEvent={this._onDragEvent}
                    saveImageFileInExtStorage={this.props.saveImageFileInExtStorage}
                    showNativeButtons={this.props.showNativeButtons}
                    showTitleLabel={this.propsshowTitleLabel}
                    viewMode={this.props.viewMode}
                    maxSize={this.props.maxSize}/>
                </View>
                <View style={{flex:0.3}}>
                <DesignSignatureUI
                   saveSign={() => {this.saveSign()}}
                   resetSign={() => {this.resetSign()}}
                   />
                </View>
                   
            </View>
        );
    }
    saveSign() {
        if(this.state.dragged === true){
            this.signComponent.saveImage()
            this.signComponent.resetImage();
        }
    }

    resetSign() {
        this.signComponent.resetImage();
    }

    _onSaveEvent(result) {
      
        console.log("jdyfgduyfgduyfgdhfgjhgsfjks"+JSON.stringify(result.pathName));
    }
    _onDragEvent() {
        this.setState({dragged:true})
        console.log("dragged");
    }
}

const styles = StyleSheet.create({
    signature: {
        flex: 1,
        borderColor: '#000033',
        borderWidth: 1,
    },
});

`

**Comment by sostenesg7** [comment]
I had the same problem on android 9.
I solve it by changing the line **140** of **/node_modules/react-native-signature-capture/android/src/main/java/com/rssignaturecapture/RSSignatureCaptureMainView.java**

`
final void saveImage() {

      String root = getContext().getCacheDir().toString(); //--<<Change this
...
`
As i need save the signature temporarily i'm saving on cache dir, you can choose your specific directory like your application data directory.

Look at: https://developer.android.com/training/data-storage/files   for more dirs;

**Comment by sostenesg7** [comment]
Look at: #146

**Comment by RavindraMaddukuri** [comment]
I already solved it by making changes in "nodemodules/react-native-signature-capture/android/src/main/java/com/rssignaturecapture/RSSignatureCaptureMainView.java"  for android. once look at the issue: #102
