### ISSUE TITLE
undefined is not a function (evaluating `UIManager.getViewManagerConfig(`RSSignatureView`)`)

### ISSUE THREAD

**Issue by KaeganClark** [RepairShopr/react-native-signature-capture#192]
I'm trying to test this feature to see if it is what I want to use. However in using the sample code I come up with this error when I try to "Reset" the sign screen.

`import {StyleSheet, View, Text, TouchableHighlight} from 'react-native';
import SignatureCapture from 'react-native-signature-capture';

export default class Signature extends Component {

    saveSign() {
        this.refs.sign.saveImage();
    }

    resetSign() {
        this.refs.sign.resetImage();
    }

    _onSaveEvent(result) {
        //result.encoded - for the base64 encoded png
        //result.pathName - for the file path name
        console.log(result);
    }
    _onDragEvent() {
         // This callback will be called when the user enters signature
        console.log("dragged");
    }

    render() {
        return (
            <View style={{ flex: 1, flexDirection: "column" }}>
                <Text style={{alignItems:"center",justifyContent:"center"}}>Signature Capture Extended </Text>
                <SignatureCapture
                    style={[{flex:2},styles.signature]}
                    ref="sign"
                    onSaveEvent={this._onSaveEvent}
                    onDragEvent={this._onDragEvent}
                    saveImageFileInExtStorage={false}
                    showNativeButtons={false}
                    showTitleLabel={true}
                    viewMode={"landscape"}/>

                <View style={{ flex: 1, flexDirection: "row" }}>
                    <TouchableHighlight style={styles.buttonStyle}
                        onPress={() => { this.saveSign() } } >
                        <Text>Save</Text>
                    </TouchableHighlight>

                    <TouchableHighlight style={styles.buttonStyle}
                        onPress={() => { this.resetSign() } } >
                        <Text>Reset</Text>
                    </TouchableHighlight>

                </View>

            </View>
        );
    }
}

const styles = StyleSheet.create({
    signature: {
        flex: 2,
        borderColor: '#000033',
        borderWidth: 1,
    },
    buttonStyle: {
        flex: 1, justifyContent: "center", alignItems: "center", height: 50,
        backgroundColor: "#eeeeee",
        margin: 10
    }
});`

**Comment by mccabemj** [comment]
@KaeganClark This is a problem we have faced in v0.4.10. We downgraded to v0.4.9 and its fine. Down to this PR - https://github.com/RepairShopr/react-native-signature-capture/pull/158

**Comment by kashifsulaiman** [comment]
I think you should mention the react native version compatible code in the README.md.
I've an app using react-native@0.54.2, and it's working with `UIManager.RSSignatureView` instead of `UIManager.getViewMangerConfig('RSSignatureView')` in the ` node_modules/react-native-signature-capture/SignatureCapture.js`
