### ISSUE TITLE
"RSSignatureView" was not found in theUIManager. 

### ISSUE THREAD

**Issue by gilshaan** [RepairShopr/react-native-signature-capture#193]
In android its working fine but in ios its showing error "RSSignatureView" was not found in theUIManager.
`dependencies": {`
   ` "react": "16.9.0",`
    `"react-native": "0.61.1",`
   ` "react-native-signature-capture": "^0.4.10"`
 ` }`

**Comment by gilshaan** [comment]
![Simulator Screen Shot - iPhone X - 2019-09-27 at 14 36 36](https://user-images.githubusercontent.com/55443224/65757728-59588300-e135-11e9-86bc-3aa6cb01fa78.png)

**Comment by gilshaan** [comment]
Fixed error by adding below podspec to podfile :
`pod 'react-native-signature-capture', :path => '../node_modules/react-native-signature-capture/react-native-signature-capture.podspec'`

**Comment by gabrielgvDOTcom** [comment]
thanks @gilshaan, after 1 year you answer works
