### ISSUE TITLE
Not working with React Native 0.11.0

### ISSUE THREAD

**Issue by achang28** [RepairShopr/react-native-signature-capture#2]
Hello.  Wondering whether you are having a problem as well.  This is the Xcode error I keep getting when the React Native component is invoked...
![screen shot 2015-09-23 at 10 00 58 pm 2](https://cloud.githubusercontent.com/assets/3760499/10065689/bb54446a-623e-11e5-9f94-759b86bb1515.png)

**Comment by theinventor** [comment]
Just a note, we have this working on a pretty new react native (0.15.0)

**Comment by jedt** [comment]
For version 0.2 I can confirm that we have this currently working with RN 0.15
