### ISSUE TITLE
The resetImage method does not work on iOS.

### ISSUE THREAD

**Issue by gmarinosyan** [RepairShopr/react-native-signature-capture#20]
When calling the resetImage method of the component, this error is thrown:

`ExceptionsManager.js:61 React.findNodeHandle is not a function`

I was able to fix this by replacing React with ReactNative. But now a new error is thrown, saying:

`ExceptionsManager.js:76 Argument 1 (NSInteger) of RCTUIManager.dispatchViewManagerCommand must not be null`

It seems that line 76 in SignatureCapture.js (`UIManager.RSSignatureView.Commands.resetImage`) is returning a null value. With further inspection I found that the `UIManager.RSSignatureView.Commands` object itself is empty. I am running RN 0.30.0. Any ideas for what could be causing this issue?

**Comment by BigPun86** [comment]
+1

**Comment by jedt** [comment]
This is now fixed kindly check npm version 0.4.3
