### ISSUE TITLE
Not work after react native >= 0.28

### ISSUE THREAD

**Issue by HaydnChen** [RepairShopr/react-native-signature-capture#21]
1.React.findNodeHandle is not a function 
2.getPackages() now is moved into MainApplication, there should be an activity in RSSignatureCapturePackage constructor, what should it be? new RSSignatureCapturePackage(new MainActivity())?

**Comment by jedt** [comment]
I tested this and is now fixed. Thanks @katanabe !

**Comment by BigPun86** [comment]
Getting same issue -> RN 32.1 & SignatureCapture 0.4.2
