### ISSUE TITLE
Base64 encoding has line breaks on Android

### ISSUE THREAD

**Issue by silentsilas** [RepairShopr/react-native-signature-capture#221]
Not sure why this is happening. I even looked at the Java code and saw nothing wrong. But I had to remove all linebreaks from the `encoded` property for my base64 decoder to work. Works as intended on iOS.

react "16.9.0
react-native: 0.62.2
react-native-signature-capture: ^0.4.10
Android 10

**Comment by Amit-Singh-Phartiyal** [comment]
Yes, same issue for me. It got me a while to figure out why its working on iOS and not in android.

**Comment by leeferfeefer** [comment]
https://github.com/RepairShopr/react-native-signature-capture/issues/195

**Comment by silentsilas** [comment]
I'll close this one since @leeferfeefer 's is more descriptive and includes a potential fix.
