### ISSUE TITLE
When I click save, the signature on the panel is cleared

### ISSUE THREAD

**Issue by zhuiye** [RepairShopr/react-native-signature-capture#229]
Why does the signature on the panel be cleared after clicking to save the picture? I read the code and did not call the erase method. I posted the following comment

```Objective-c
// Both of these methods needs to be called from the main thread so the
// UI can clear out the signature.
RCT_EXPORT_METHOD(saveImage:(nonnull NSNumber *)reactTag) {
	dispatch_async(dispatch_get_main_queue(), ^{
		[self.signView saveImage];
	});
}
```
What if I want to make the signature unclear

Can someone give a plan, thank you

**Comment by chrisrekki** [comment]
+1 Having the same issue

**Comment by karencplara** [comment]
For fix, you can delete [self erase]  in  ios/PPSSignatureView.m. 
below the following code: 
UIImage *signatureImg;
UIImage *snapshot = [self snapshot];
[self erase]; //remove this line.

**Comment by brunofrigeri** [comment]
+1 Having this issue

**Comment by Kandom** [comment]
Remove [self erase] within
- (UIImage *)signatureImage: (BOOL) rotatedImage withSquare:(BOOL) square
in ios/PSSignatureView.m

**Comment by Cado21** [comment]
im using react native and i can't find any PPSSignatureView.m files in my ios folder

**Comment by Cado21** [comment]
> For fix, you can delete [self erase] in ios/PPSSignatureView.m. below the following code: UIImage *signatureImg; UIImage *snapshot = [self snapshot]; [self erase]; //remove this line.

how do i navigate to the file? i am using react native and not seeing any PPSSignatureView.m files inside my ios folder

**Comment by zhuiye** [comment]
> > For fix, you can delete [self erase] in ios/PPSSignatureView.m. below the following code: UIImage *signatureImg; UIImage *snapshot = [self snapshot]; [self erase]; //remove this line.
> 
> how do i navigate to the file? i am using react native and not seeing any PPSSignatureView.m files inside my ios folder
![image](https://user-images.githubusercontent.com/26075200/147719375-17343883-02a3-4f49-8433-cd6aafbe39a8.png)


![image](https://user-images.githubusercontent.com/26075200/147719194-d3ee52e2-a1ec-4823-bf31-e7953939ed14.png)
