### ISSUE TITLE
Android - getExternalStorageDirectory is deprecated in API level 29

### ISSUE THREAD

**Issue by idanlo** [RepairShopr/react-native-signature-capture#230]
getExternalStorageDirectory is deprecated - https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory().

Currently saving the signature file does not work because this folder is not accessible, this should be changed

**Comment by NeliHarbuzava** [comment]
+1

**Comment by avenyproduction** [comment]
I also have this issue. Has anyone managed to solve it? I have tried with this pull request attached here but it doesn't work
