### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by DCKT** [RepairShopr/react-native-signature-capture#25]
Hello,

After linked the package, I got this error : 
I'm using react-native 0.31.0, when I remove the line of my MainApplication the build is ok

<img width="804" alt="capture d ecran 2016-09-06 a 14 54 03" src="https://cloud.githubusercontent.com/assets/1548421/18274250/cf76eb62-7441-11e6-9f88-a9c4636d9971.png">

Thanks

**Comment by DCKT** [comment]
After some search, it appears the module missing implements of `ReactContextBaseJavaModule`
More here : 
https://github.com/facebook/react-native/blob/3d1b79cd156e8055eab54cefa84a3532572be82c/ReactAndroid/src/main/java/com/facebook/react/modules/intent/IntentModule.java#L28

**Comment by katanabe** [comment]
Hello @DCKT

How did you install this package?

I'm using this library on RN v.0.32.0
Please try this:
```sh
npm install --save 'git+https://github.com/RepairShopr/react-native-signature-capture.git'
```

**Comment by DCKT** [comment]
Hi @katanabe Thanks for your answer, it appears it works when I follow your command. Thanks !
