### ISSUE TITLE
[Android] Multiple Gradle Warnings: Task uses output without declaring an explicit or implicit dependency.

### ISSUE THREAD

**Issue by reyesrico** [RepairShopr/react-native-signature-capture#279]
After installing manually `react-native-signature-capture` library and while running the project in android, it is being displayed at least 9 warnings regarding task dependencies internally: 

```
Gradle detected a problem with the following location: 'C:\...\node_modules\react-native-signature-capture\android\build\intermediates\packaged_res\debug'. Reason: Task ':reactnativesignaturecapture:parseDebugLocalResources' uses this output of task ':react-native-signature-capture:packageDebugResources' without declaring an explicit or implicit dependency. 
```

Tasks that are generating warnings:
     **Task 1  uses => Task 2**
1. `:reactnativesignaturecapture:packageDebugAssets`"   => `":reactnativesignaturecapture:compileDebugShaders"`
2. `":reactnativesignaturecapture:packageDebugResources"` => `":reactnativesignaturecapture:generateDebugResValues"`
3. `":reactnativesignaturecapture:parseDebugLocalResources"`=> `":reactnativesignaturecapture:packageDebugResources"`
4. `":reactnativesignaturecapture:compileDebugLibraryResources"` => `":reactnativesignaturecapture:packageDebugResources"`
5. `":reactnativesignaturecapture:generateDebugRFile"` => `":reactnativesignaturecapture:parseDebugLocalResources"`
6. `":reactnativesignaturecapture:compileDebugJavaWithJavac"` =>`":reactnativesignaturecapture:compileDebugAidl"`
7. `":reactnativesignaturecapture:bundleLibCompileToJarDebug"` => `":reactnativesignaturecapture:generateDebugRFile"`
8. `":reactnativesignaturecapture:bundleLibRuntimeToJarDebug"` => `":reactnativesignaturecapture:compileDebugJavaWithJavac"`
9. `":reactnativesignaturecapture:copyDebugJniLibsProjectOnly"` => `":reactnativesignaturecapture:stripDebugDebugSymbols"`

Please your help to get a solution or a possible workaround.

**Comment by reyesrico** [comment]
These warnings are not displayed when using `yarn react-native link react-native-signature-capture`, instead of updating files manually for Android.

**Comment by hellogbg** [comment]
Having the same issue, but I can't solve it with `yarn react-native link react-native-signature-capture`

this is the error message I get when I try to run `./gradlew assembleRelease`
```
* What went wrong:
A problem was found with the configuration of task ':react-native-signature-capture:copyReleaseJniLibsProjectAndLocalJars' (type 'LibraryJniLibsTask').
  - Gradle detected a problem with the following location: 'xxxxxx/node_modules/react-native-signature-capture/android/build/intermediates/stripped_native_libs/release/out'.
    
    Reason: Task ':react-native-signature-capture:copyReleaseJniLibsProjectAndLocalJars' uses this output of task ':reactnativesignaturecapture:stripReleaseDebugSymbols' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
```

I am on RN 0.72.3
react-native-signature-capture worked for me before in this same project, but after I removed node_modules and run npm install this keeps happening. I have cleaned the project and it works for ios but not for Android

**Edit:**
It seems to be a problem with Gradle 8
