### ISSUE TITLE
React.findNodeHandle is not a function

### ISSUE THREAD

**Issue by icynoangel** [RepairShopr/react-native-signature-capture#29]
On commit 321a687520a949c6994e85858be5ed49989035e3 imports of React and ReactNative were changed.
A fix for this might be to change line 68 in SignatureCapture.js from:
React.findNodeHandle(this)
to:
ReactNative.findNodeHandle(this)

and the same change for line 78.

**Comment by abimelex** [comment]
Relates to: https://github.com/RepairShopr/react-native-signature-capture/issues/20

**Comment by BigPun86** [comment]
+1

**Comment by icynoangel** [comment]
Guys, I have submitted a pull request for this issue, if you get the time to review it and maybe merge it into master. Thanks!

[https://github.com/RepairShopr/react-native-signature-capture/pull/32](url)
