### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by Ledda** [RepairShopr/react-native-signature-capture#3]
Hey guys, love this plugin to bits! 
Any chance of one being developed for Android or know anyone who would know to develop one for Android? 
Thanks

**Comment by theinventor** [comment]
We will need it in a couple months - if you can wait that long..


Troy Anderson

**Comment by Ledda** [comment]
One of my apps is being used by a Client and they have been asking about Android version of the app.. Ill just tell them to wait a little longer. They understand that I cannot develop Android and will have to wait until a plugin of some sort is available for me to use :)
End of the day I really really like the one you guys came up with for iOS so I am not going to complain!

Also is there somewhere I can donate?

Regards, 
Alex

**Comment by achang28** [comment]
I, too am down to donate

**Comment by Ledda** [comment]
@theinventor Any news? 

If there are any links to donate to you let me know and ill gladly contribute :+1:

**Comment by theinventor** [comment]
@Ledda still a couple months away on our side probably. It's up to @jedt if he wants to take this on outside of work - I know he is a busy guy though :smile:

**Comment by Ledda** [comment]
@jedt Whats your schedule like coming up to Christmas? Email me if you're interested in this :)

**Comment by lazarte** [comment]
Any android update on this?

**Comment by madisvain** [comment]
This is of interest to us also. Would be glad to help.

**Comment by Ledda** [comment]
@theinventor Hey just checking in. Any news on this? Happy to contribute if that is the issue :+1:

**Comment by ivesy85** [comment]
I'd love this feature for android! I can donate also.

**Comment by dangnelson** [comment]
+1

**Comment by theinventor** [comment]
Just an update from us (RepairShopr) - we'll probably be investing developer time in this ourselves around February.

This is on our roadmap for when we begin targeting Android with our mobile app, but it's coming after we add one more very large feature to our iOS app.

If anyone wants to introduce us to an android/react-native freelancer we'll sponsor this sooner - otherwise we'll probably do it around February.

**Comment by Ledda** [comment]
I have a contact possibly. I will reach out to them now and ask them if they can develop this.

Thanks for the update!

**Comment by guizmaii** [comment]
+1

**Comment by rmevans9** [comment]
Heads up everyone that has been watching this - I have started on a Android version. i used a freely available tutorial to get a canvas setup to allow for drawing. I have pushed up my first pass at adding Android support just now and will be looking to get feature parity within the next 24 hours. If anyone wants to pitch in feel free. I will open a PR once I have gotten feature parity.

https://github.com/rmevans9/react-native-signature-capture

**Comment by Ledda** [comment]
absolute legend! i wish i could help :)

**Comment by rmevans9** [comment]
Quick update, I have Android seemingly working. I still have some more to go to get it to where I want it but if you pull from my repo you can get a signature and get the file location and base64 just like the iOS counterpart. The line when drawing looks a bit choppy compared to iOS but I am not overly concerned about that at this point.

**Comment by Ledda** [comment]
amazing! hopefully it gets merged soon :) I will have a look at your repo when i get back into it next week!!

**Comment by dangnelson** [comment]
Until Android support is merged, it would be great to have an explicit warning at the top of the docs that this is iOS only.

**Comment by theinventor** [comment]
@rmevans9 - any chance you can post a video of the app experience you've got on your branch?

(take a short video of what the app/signature capture looks like)

If it's solid and a couple other users try it and +1 --- we'll merge

**Comment by theinventor** [comment]
Can others weigh in, @jedt ? - should the Examples go in another repo, or are they ok in this one?

example; https://github.com/RepairShopr/react-native-signature-capture/compare/master...rmevans9:master#diff-83ccf47f50b4b770f7aefd1fa0223f43R1

**Comment by rmevans9** [comment]
@theinventor Yeah, I can probably get something together but I probably won't be able to till next week sometime as I am crunching to get some stuff done on my current project. I can tell you that it doesn't look half bad currently and works as well as I would expect it to. The only thing is, as I mentioned in my last message, the line looks a bit more choppy then what iOS looks like but for my uses that is a non-issue thus I have not spent any time looking into it.

**Comment by rmevans9** [comment]
@theinventor I can certainly move the examples out if needed. I just found it easy to put the example side by side. In addition a lot of other libraries do the same so I just followed that pattern. If you guys want that moved out I would be more then happy to throw it in a different repo.

**Comment by jedt** [comment]
@theinventor I'll check the PR, it might take a 2-3 days probably.

**Comment by zoontek** [comment]
I've started working on the support when I see the @rmevans9 job.
Maybe I can take a look to check why the drawing looks choppy.

**Comment by theinventor** [comment]
also fyi everyone - jedt will be getting his dev env setup for android to be able to manually test the android work, any videos/screenshots/etc showing android working could help speed us up in some super basic QA. Might have an update on this in a few business days..

**Comment by rmevans9** [comment]
@theinventor I completely forgot to do that. Sorry! Here is what I put together in about 30 seconds of time from the app I am currently working on.

http://g.recordit.co/tDtpoBXOmH.gif

**Comment by jedt** [comment]
Just an update, I was able to setup the android port, It is indeed a good starting point, thanks and good job @rmevans9. 

But unfortunately, I also need more time to investigate the choppy lines.

<img width="1432" alt="screen shot 2016-01-13 at 5 44 52 pm" src="https://cloud.githubusercontent.com/assets/173964/12290410/9bdf1eda-ba1c-11e5-8c83-031331ca869c.png">

**Comment by jedt** [comment]
I've merged the PR and added setup instructions to the README in case anyone would want to contribute to the android support

https://github.com/RepairShopr/react-native-signature-capture#how-to-setup-android

Closing this issue for now.

**Comment by jedt** [comment]
Happy to update that choppy lines are now fixed and Android is now fully supported. 
I rewrote @rmevans9 work and I ported this repo: https://github.com/gcacace/android-signaturepad instead.

**Comment by rmevans9** [comment]
glad that my work at least got support started!

**Comment by Ledda** [comment]
Great work guys! Cannot thank you enough!!
