### ISSUE TITLE
Make dashed signature lines optional

### ISSUE THREAD

**Issue by Juanelorganelo** [RepairShopr/react-native-signature-capture#37]
Hi, I want to remove the dashed lines in the signature pad without going in to native code. Something like

``` javascript
<SignatureCapture
    displayDashedBorders={false}
/>
```

Is it doable?

**Comment by ajwhite** [comment]
Hell, don't even hard-code these in. Allow the React side to style it and add children.

```html
<SignatureCapture style={styles.dottedBorder}>
  <View style={styles.dashedLines} />
</SignatureCapture>
```

**Comment by kevinnguy** [comment]
For a quick fix, you can comment out `[sign addSubview:titleLabel];` in `RSSignatureView.m`.

**Comment by gerauf** [comment]
I'm still having trouble with this, @ajwhite what styles did you use in your styles.dashedLines and styles.dashedBorder?

Cheers

**Comment by Tom32i** [comment]
I just submitted a simple PR that would allow us to disable these dashed lines on demand: #55

**Comment by ajwhite** [comment]
@gerauf that was just an example -- there is no support for that within this library. I had forked it to incorporate the new behavior, unfortunately that is private at this time.
