### ISSUE TITLE
Unable to sign 

### ISSUE THREAD

**Issue by uc-asa** [RepairShopr/react-native-signature-capture#47]
Hello team,

I have installed then run my app then my screen look this.

![image](https://cloud.githubusercontent.com/assets/16412197/22370044/52cd3d20-e4b5-11e6-91df-012bfac80a73.png)

And unable to sign please help and suggest me.

**Comment by jedt** [comment]
Try setting the height of the device on the signature component.

ex. 

require('Dimensions').get('window').height

**Comment by uc-asa** [comment]
Can you provide example

**Comment by uc-asa** [comment]
Thank you I Have done it.
