### ISSUE TITLE
Remove dotted line

### ISSUE THREAD

**Issue by uc-asa** [RepairShopr/react-native-signature-capture#48]
Hello Team,

I'm using this but facing problem to remove dotted line like

![image](https://cloud.githubusercontent.com/assets/16412197/22421791/0349985a-e70f-11e6-9b11-e5124ffabba2.png)

For android and iOS both, please suggest
And also need to decode image for web module

**Comment by kevinnguy** [comment]
Duplicate https://github.com/RepairShopr/react-native-signature-capture/issues/37

**Comment by Tom32i** [comment]
I just submitted a simple PR that would allow us to disable these dashed lines on demand: #55
