### ISSUE TITLE
The signature image is not stored in the folder (Android)

### ISSUE THREAD

**Issue by hielfx** [RepairShopr/react-native-signature-capture#56]
After using the onSaveEvent method, the result correctly return the path and the base64 encoding, however when I navigate to the given path, the save_signature folder is empty (also the image isn't displayed in the gallery)

Using Android with RN v0.40 and component version v0.4.5

**Comment by Zhipan1** [comment]
try setting `saveImageFileInExtStorage` to true on android

**Comment by john1jan** [comment]
Yes setting saveImageFileInExtStorage makes the image to be stored in external storage. then it can be used

**Comment by hielfx** [comment]
Thanks! I didn't notice that property in the README

**Comment by MrHubble** [comment]
Where is the image stored on Android if `saveImageFileInExtStorage` is set to `false`?

**Comment by john1jan** [comment]
it will be saved on Android [Internal Storage](https://developer.android.com/guide/topics/data/data-storage.html#filesInternal).
By default, files saved to the internal storage are private to your application and other applications cannot access them (nor can the user). When the user uninstalls your application, these files are removed.

**Comment by khrizt** [comment]
Not true, if `saveImageFileInExtStorage` is set to false the library crashes if it has not storage permissions

**Comment by khrizt** [comment]
In fact I've created a pull request to solve this https://github.com/RepairShopr/react-native-signature-capture/pull/98

**Comment by pranav-pandey** [comment]
@john1jan But obviously, we would need to access the image. It says the path as `/storage/emulated/0/saved_signature/signature.png` but the saved-signature folder doesn't exist. I have no external storage with my device.

**Comment by peterent** [comment]
This does not work on Android 9. The onSaveEvent parameter comes back as:
 {pathName: "/storage/emulated/0/saved_signature/signature.png", encoded: "iVBORw0KGg...."}
When I dump the contents of RNFS.DocumentDirectoryPath+result.pathName it shows nothing in this directory. I have no external storage on my device, although I did set up permissions to read and write to external storage which were granted.

So what are we supposed to do. This issue is not closed.

**Comment by KaroUlm** [comment]
I have the same error, file path is shown in Text but none signature image is shown. Trying to send this signature cause an error. I don't want to save all signatures to external storage. I only need this image for my specific app. Please fix this issue. IOS works fine, Android not.

**Comment by romk1n** [comment]
👍

**Comment by renielDev** [comment]
Same error Im having too. Is there a fix for this? 

iOS working fine. For android, if `saveImageFileInExtStorage` is set to true it will work if the permissions are granted. but if it's set false, it doesnt work. File doesnt get saved internally.

**Comment by mertlena** [comment]
> Where is the image stored on Android if `saveImageFileInExtStorage` is set to `false`?

it is a prop of `SignatureCapture` component

**Comment by RigoTheDev** [comment]
@mertlena I think he means where the actual file is stored on the device.
