### ISSUE TITLE
Android installation

### ISSUE THREAD

**Issue by dangnelson** [RepairShopr/react-native-signature-capture#7]
I'm trying to install on an existing project, and followed the instructions given. I'm running React Native 0.18.0-rc

When trying to launch the app I get the following error:

    * What went wrong:
    A problem occurred configuring project ':app'.
    > Cannot evaluate module reactnativesignaturecapture : Configuration with name 'default' not found.

**Comment by dangnelson** [comment]
I had to update the version in my package.json file to 0.4.0

Any reason you don't have the release history in Github?

**Comment by theinventor** [comment]
we are beginner maintainers! :)

**Comment by dangnelson** [comment]
👍
