### ISSUE TITLE
Option to rotate??

### ISSUE THREAD

**Issue by CharlieOrlando** [RepairShopr/react-native-signature-capture#71]
Any chance we can get an option to rotate the final signature before saving??

**Comment by john1jan** [comment]
Why do you want to rotate the signature ?

**Comment by CharlieOrlando** [comment]
The saved signature needs to be rotated 270 degrees. You can do it with a transform, but it would be nice to not save a sideways image

**Comment by CharlieOrlando** [comment]
Nevermind. Just saw the rotateClockwise prop
