### ISSUE TITLE
Portrait App

### ISSUE THREAD

**Issue by dangnelson** [RepairShopr/react-native-signature-capture#8]
I have an app that I want keep in portrait. I was able to rotate and contain the signature component in iOS like so:

<img width="375" alt="screen shot 2016-01-14 at 12 01 18 pm" src="https://cloud.githubusercontent.com/assets/8430446/12331199/9345a61e-bab6-11e5-9dc8-21f7c8818ee3.png">

The issue I'm having is with Android. When running in a Genymotion emulator, the emulator starts freaking out and rotates back and forth until it crashes. I'm guessing this has to do with the Orientation being set by react-native-signature-capture.

Is this something that could be conditional, or simply not done on the assumption the developer could set it themselves?

**Comment by dangnelson** [comment]
I forked a version that removes the orientation flip for now:
https://github.com/dangnelson/react-native-signature-capture

**Comment by dangnelson** [comment]
Here is is working on Android:
<img width="435" alt="screen shot 2016-01-14 at 12 14 00 pm" src="https://cloud.githubusercontent.com/assets/8430446/12331636/61fba0f2-bab8-11e5-9421-d886cd72a769.png">

**Comment by jedt** [comment]
> Is this something that could be conditional, or simply not done on the assumption the developer could set it themselves?

Yeah maybe.. we'll let this issue open so other people may chime in.

**Comment by theinventor** [comment]
I think it makes sense to have a rotation_lock: true property or something..

+1

**Comment by emily-jny** [comment]
@dangnelson @jedt 
How did you change the signature part to portrait? Is there any css I can add to change it? Thanks.

**Comment by dangnelson** [comment]
The android version seemed to do this automatically. I had to make a duplicate iOS version that used rotation to accomplish it:


Get Dimensions:

    import Dimensions from 'Dimensions';
    var windowWidth = Dimensions.get('window').width;
    var windowHeight = Dimensions.get('window').height;

Wrap Signature Component in rotated View:

    <View style={styles.signWrap}>   
      <View style={styles.signRotate}>
        <SignatureCapture onSaveEvent={this._onSaveEvent}/>
      </View>
    </View>

Style of Rotated View:

    signWrap: {
	  height: windowHeight/2.5,
    },
    signRotate: {
	  transform: [{rotate: "-90deg"}],
	  position: 'absolute',
	  height: windowWidth,
	  width: windowHeight/2.5,
	  opacity: .97,
	  top: -( (windowWidth - (windowHeight/2.5))/2 ),
	  left: (windowWidth - (windowHeight/2.5))/2,
	  right:0,
	  bottom:0,
    },

**Comment by emily-jny** [comment]
@dangnelson 
Got it working. Thank you so much

**Comment by niksajanjic** [comment]
I don't think viewMode works either on iOS, passing 'portrait' or 'landscape' to it makes no difference at all. My signature takes whole screen and if I'm in portrait mode signature will be in landscape. If I flip application to landscape mode and open signature, then signature is in portrait.

**Comment by paulailincai** [comment]
Hi, I used activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT); in the NPM module: android/src/main/java/com/rsssignaturecapture/utils/RSSignatureCaptureMainView.java.
By default it is set to ....LANDSCAPE.

**Comment by donovantc** [comment]
@dangnelson thanks for the tip! Another question on this topic: how did you rotate the image upon saving? When I use the styling you suggested, it is in portrait but when it saves, the signature is saved as though it is in landscape?

**Comment by dangnelson** [comment]
I believe my guide above is out of date. Last time I checked portrait is now supported.

**Comment by srichallamalla935** [comment]
Can someone help me out viewmode is not working  in ios

**Comment by lynmije** [comment]
> @dangnelson thanks for the tip! Another question on this topic: how did you rotate the image upon saving? When I use the styling you suggested, it is in portrait but when it saves, the signature is saved as though it is in landscape?

Do you have any fixed on this issue?

**Comment by R4DIC4L** [comment]
There is a rotateClockwise property on the SignatureCapture that rotates the signature clockwise. I tried rotating the view with -90 degrees but it doesn't work, only rotating 90 degrees worked for me in iOS simulator. I am still thinking of changing the signature library, as this one has given me enough issues.
