### ISSUE TITLE
peerDependencies need updating

### ISSUE THREAD

**Issue by zachheine** [RepairShopr/react-native-signature-capture#9]
`error code EPEERINVALID`
`error peerinvalid The package react-native@0.18.0-rc does not satisfy its siblings' peerDependencies requirements!`
`error peerinvalid Peer react-native-signature-capture@0.4.0 wants react-native@>=0.17`

**Comment by zachheine** [comment]
Well, maybe not: https://github.com/npm/npm/issues/8854?  What is the recommended workaround?

**Comment by jedt** [comment]
Try downgrading react-native to 0.17.0?

**Comment by jedt** [comment]
I will fix the peer dependency once 0.18.0 is released right now it's still a release candidate
